{{- range $name, $config := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "backend-parameters.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml $config.stringData | nindent 2 }}
---
{{- end }}
